version: "3"

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "3000:80"
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    node-app:
        image: node-app
        environment: 
            - PORT=3000
        depends_on: 
            - mongo-db
        # env_file: 
        #    - ./.env
    mongo-db:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        volumes: 
            - mongo-data:/data/db
    
    redis-db:
        image: redis
        depends_on: 
            - mongo-db

volumes: 
    mongo-data: