version: "3"

services: 
    node-app:
        image: node-app
        build: .
        ports: 
            - "3000:3000"
        environment: 
            - PORT=3000
        volumes: 
            - ./:/app:ro
            - node-modules:/app/node_modules
        # env_file: 
        #    - ./.env

volumes: 
    node-modules: